var hierarchy =
[
    [ "AttendanceRecord", "struct_attendance_record.html", null ],
    [ "AudioStream", "struct_audio_stream.html", null ],
    [ "AutomationEvent", "struct_automation_event.html", null ],
    [ "AutomationEventList", "struct_automation_event_list.html", null ],
    [ "BoneInfo", "struct_bone_info.html", null ],
    [ "BoundingBox", "struct_bounding_box.html", null ],
    [ "Branch", "class_branch.html", null ],
    [ "BranchList", "class_branch_list.html", null ],
    [ "Camera2D", "struct_camera2_d.html", null ],
    [ "Camera3D", "struct_camera3_d.html", null ],
    [ "CartItem", "struct_cart_item.html", null ],
    [ "Color", "struct_color.html", null ],
    [ "FilePathList", "struct_file_path_list.html", null ],
    [ "float16", "structfloat16.html", null ],
    [ "float3", "structfloat3.html", null ],
    [ "Font", "struct_font.html", null ],
    [ "GlyphInfo", "struct_glyph_info.html", null ],
    [ "GridPoint", "struct_grid_point.html", null ],
    [ "Image", "struct_image.html", null ],
    [ "LoginAccount", "struct_login_account.html", null ],
    [ "ManagementUI", "class_management_u_i.html", null ],
    [ "MapGraph", "class_map_graph.html", null ],
    [ "MapRoute", "struct_map_route.html", null ],
    [ "Material", "struct_material.html", null ],
    [ "MaterialMap", "struct_material_map.html", null ],
    [ "Matrix", "struct_matrix.html", null ],
    [ "MenuItem", "struct_menu_item.html", null ],
    [ "MenuLookup", "class_menu_lookup.html", null ],
    [ "Mesh", "struct_mesh.html", null ],
    [ "Model", "struct_model.html", null ],
    [ "ModelAnimation", "struct_model_animation.html", null ],
    [ "ModelSkeleton", "struct_model_skeleton.html", null ],
    [ "Music", "struct_music.html", null ],
    [ "NPatchInfo", "struct_n_patch_info.html", null ],
    [ "OpeningHours", "class_opening_hours.html", null ],
    [ "OperatingSchedule", "class_operating_schedule.html", null ],
    [ "Order", "struct_order.html", null ],
    [ "OrderQueue", "class_order_queue.html", null ],
    [ "Product", "struct_product.html", null ],
    [ "Ray", "struct_ray.html", null ],
    [ "RayCollision", "struct_ray_collision.html", null ],
    [ "Rectangle", "struct_rectangle.html", null ],
    [ "RenderTexture", "struct_render_texture.html", null ],
    [ "RestaurantChain", "class_restaurant_chain.html", null ],
    [ "rlDrawCall", "structrl_draw_call.html", null ],
    [ "rlRenderBatch", "structrl_render_batch.html", null ],
    [ "rlVertexBuffer", "structrl_vertex_buffer.html", null ],
    [ "Schedule", "class_schedule.html", [
      [ "WorkSchedule", "class_work_schedule.html", [
        [ "FullTimeSchedule", "class_full_time_schedule.html", null ],
        [ "SelfRegisteredSchedule", "class_self_registered_schedule.html", null ]
      ] ]
    ] ],
    [ "ScheduleService", "class_schedule_service.html", null ],
    [ "Shader", "struct_shader.html", null ],
    [ "ShiftManager", "class_shift_manager.html", null ],
    [ "Sound", "struct_sound.html", null ],
    [ "Texture", "struct_texture.html", null ],
    [ "Timekeeping", "class_timekeeping.html", null ],
    [ "Transform", "struct_transform.html", null ],
    [ "User", "class_user.html", [
      [ "Employee", "class_employee.html", [
        [ "Manager", "class_manager.html", [
          [ "BranchManager", "class_branch_manager.html", null ]
        ] ]
      ] ]
    ] ],
    [ "Vector2", "struct_vector2.html", null ],
    [ "Vector3", "struct_vector3.html", null ],
    [ "Vector4", "struct_vector4.html", null ],
    [ "VrDeviceInfo", "struct_vr_device_info.html", null ],
    [ "VrStereoConfig", "struct_vr_stereo_config.html", null ],
    [ "Warehouse", "class_warehouse.html", null ],
    [ "Wave", "struct_wave.html", null ]
];